stages:
  - install
  - test

default:
    image:
        name: docker-hub.squiz.net/docker/base-images/node:22-alpine

install-dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

run-tests:
  stage: test
  script:
    - npm test